---
- name: Install Docker
  include_role:
      name: docker

- name: Remove swapfile from /etc/fstab
  mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
      backup: yes
  with_items:
      - swap
      - none
- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

