---
- name: Install docker requirements
    apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
    with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

- name: Add Docker GPG key
    apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

- name: Verify that we now have the key with the fingerprint 
    apt-key:
        id: 0EBFCD88
        state: present


- name: Add docker repository
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bionic stable
        state: present
        update_cache: true

- name: Install Docker
    apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    notify:
        - docker status
